"""
Django settings for Gestion_Livraison project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kx!59uw#qh_#bin^@4(#$t@4tsl@=hn%x83y-8v^5t)tz85#+$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


import os
import socket

# Les hôtes autorisés par défaut
ALLOWED_HOSTS = ['*']

def add_dynamic_host():
    """
    Ajoute dynamiquement l'adresse et le port actuels à ALLOWED_HOSTS si nécessaire.
    """
    try:
        # Récupérer le nom d'hôte complet
        host = socket.gethostname()
        ip_address = socket.gethostbyname(host)

        # Récupérer le port à partir des variables d'environnement
        port = os.environ.get('DJANGO_RUNSERVER_PORT', None)

        # Construire l'adresse complète (hôte:port)
        if port:
            full_address = f'{ip_address}:{port}'
        else:
            full_address = ip_address  # Par défaut, utiliser uniquement l'adresse IP

        # Ajouter dynamiquement si l'adresse n'est pas dans ALLOWED_HOSTS
        if full_address not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(full_address)
            print(f"Adresse ajoutée dynamiquement à ALLOWED_HOSTS : {full_address}")

    except Exception as e:
        print(f"Erreur lors de l'ajout dynamique d'un hôte : {e}")

# Appeler la fonction pour mettre à jour ALLOWED_HOSTS
add_dynamic_host()



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Livraisons',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'channels',
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}


ASGI_APPLICATION = "Livraisons.application"
ASGI_APPLICATION = "Gestion_Livraisons.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Redis doit être en cours d'exécution sur votre machine locale
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Obligatoire
]

ROOT_URLCONF = 'Gestion_Livraison.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gestion_Livraison.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#ajout de URL de DJANGO
# Ajout des configurations pour gérer les cookies et les origines
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",  # Adresse du frontend React
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # Adresse du frontend React
]

CSRF_COOKIE_HTTPONLY = False  # Permet au frontend de lire le cookie CSRF
CSRF_COOKIE_SAMESITE = 'Lax'  # Configure le partage des cookies
CSRF_COOKIE_SECURE = False    # Activez `True` si vous utilisez HTTPS

CORS_ALLOW_HEADERS = list(default_headers) + [
    'matricule',
    'password',
]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ]
}

# Chemin pour les fichiers téléchargés
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
