--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: fournisseurs; Type: TABLE; Schema: public; Owner: lea
--

CREATE TABLE public.fournisseurs (
    id integer NOT NULL,
    numerotelephone integer NOT NULL,
    bp character varying(5) NOT NULL,
    nom character varying(25) NOT NULL,
    quartier character varying(25) NOT NULL,
    email character varying(255) NOT NULL,
    pays character varying(255) NOT NULL,
    ville character varying(255) NOT NULL,
    CONSTRAINT fournisseurs_numerotelephone_check CHECK (((numerotelephone >= 600000000) AND (numerotelephone <= 699999999)))
);


ALTER TABLE public.fournisseurs OWNER TO lea;

--
-- Name: fournisseurs_id_seq; Type: SEQUENCE; Schema: public; Owner: lea
--

ALTER TABLE public.fournisseurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fournisseurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: fournisseurs; Type: TABLE DATA; Schema: public; Owner: lea
--

COPY public.fournisseurs (id, numerotelephone, bp, nom, quartier, email, pays, ville) FROM stdin;
1	678921475	fineB	finebiscuits	Banane	finebiscuits@gmail.com	Cameroun	yaoundé
2	699663322	tAnty	tanty	Nsam-Efoulan	tanty@gmail.com	Cameroun	yaoundé
3	678921475	za-CM	zara	Acacias	Zara@gmail.com	Cameroun	yaoundé
4	678921475	addnk	addnk	Acacias	addnk@gmail.com	Cameroun	yaoundé
\.


--
-- Name: fournisseurs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lea
--

SELECT pg_catalog.setval('public.fournisseurs_id_seq', 4, true);


--
-- Name: fournisseurs fournisseurs_email_key; Type: CONSTRAINT; Schema: public; Owner: lea
--

ALTER TABLE ONLY public.fournisseurs
    ADD CONSTRAINT fournisseurs_email_key UNIQUE (email);


--
-- Name: fournisseurs fournisseurs_pkey; Type: CONSTRAINT; Schema: public; Owner: lea
--

ALTER TABLE ONLY public.fournisseurs
    ADD CONSTRAINT fournisseurs_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

INSERT INTO fournisseurs (nom,email,numerotelephone,pays,ville,quartier,bp) VALUES
    ("tanty", "tanty@gmail.com", 678921475, "Cameroun", "yaoundé", "Acacias", "123kl"),
    ("ntfoods", "nt@gmail.com", 623147859, "Cameroun", "Douala", "Bonabéri", "mp321"),
    ("finebiscuits","fine@gmail.com",656417896,"Cameroun","Yaoundé","BiyemAssi","FB420"),
    ("zara","zara@gmail.com",632145869,"Cameroun","Yaoundé","BiyemAssi","5za10"),
    ("sephora","sephora@gmail.com",698745632,"Cameroun","Yaoundé","Nkolbisson","seph4"),
    ("lg entertainment","lg@gmail.com",699362547,"Cameroun","Yaoundé","Nkolbisson","2lg34"),
    ("chez rodrigue","rodrigue@gmail.com",699241750,"Cameroun", "Yaoundé","Jouvence","2ro04");
