# Generated by Django 5.1.2 on 2024-11-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('salaire', models.DecimalField(decimal_places=2, default=150000.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LivraisonEffectuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('nbre_livraisons', models.PositiveIntegerField()),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_effectuees', to='Livraisons.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_produit', models.TextField()),
                ('destination', models.CharField(max_length=255)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_client', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='Livraisons.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes', to='Livraisons.livreur')),
            ],
        ),
    ]
