# Generated by Django 5.1.2 on 2024-11-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivEffectuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande_id', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('ACCEPTED', 'Accepted')], default='ACCEPTED', max_length=10)),
                ('moyen_paiement', models.CharField(choices=[('ON_DELIVERY', 'On Delivery')], default='ON_DELIVERY', max_length=20)),
                ('date_paiement', models.DateField()),
                ('heure_livraison', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_state', models.CharField(max_length=50)),
            ],
        ),
    ]
