# Generated by Django 5.1.2 on 2024-11-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0003_rename_commande_id_liveffectuer_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveffectuer',
            name='customer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveffectuer',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
