# Generated by Django 5.1.2 on 2024-11-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0004_liveffectuer_customer_id_alter_liveffectuer_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idcommande', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('prixTotal', models.FloatField()),
                ('montant_livraison', models.IntegerField()),
                ('idutilisateur', models.IntegerField()),
                ('panier', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcommande', models.IntegerField()),
                ('idutilisateur', models.IntegerField()),
                ('PrixLiv', models.FloatField()),
            ],
        ),
    ]
