# Generated by Django 5.1.2 on 2024-11-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0005_commande_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='mpd',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
