# Generated by Django 5.1.2 on 2024-12-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0006_livreur_image_livreur_mpd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotDePasseHache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='livreur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
