# Generated by Django 5.1.2 on 2024-12-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0007_admin_motdepassehache_livreur_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='matricule',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
