# Generated by Django 5.1.2 on 2024-12-28 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0008_admin_matricule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveffectuer',
            old_name='order_id',
            new_name='orderId',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='orderId',
        ),
        migrations.AddField(
            model_name='livraison',
            name='id_commande',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
