# Generated by Django 5.1.2 on 2024-12-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0009_rename_order_id_liveffectuer_orderid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='orderId',
            new_name='transaction_id',
        ),
    ]
