# Generated by Django 5.1.2 on 2024-12-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0010_rename_orderid_payment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveffectuer',
            old_name='orderId',
            new_name='order_id',
        ),
    ]
