# Generated by Django 5.1.2 on 2024-12-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0011_rename_orderid_liveffectuer_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='orderId',
        ),
    ]
