# Generated by Django 5.1.2 on 2024-12-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraisons', '0012_rename_transaction_id_payment_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
